import Head from "next/head";
import Image from "next/image";

import GithubIcon from "../assets/github.svg";
import Image1 from "../assets/image1.png";
import Image2 from "../assets/image2.png";
import Image3 from "../assets/image3.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>The Legend of Aric and The Shadow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen flex flex-col items-center justify-center">
        <div
          style={{ maxWidth: "1152px" }}
          className="w-4/5  flex items-center justify-center mt-6"
        >
          {/* <h1 className="font-black text-white text-4xl"># The Legend of Aric and The Shadow</h1> */}
          <div className="text-black bg-white flex p-1">
            <Image src={GithubIcon} className="" alt="" height={32} />
          </div>
        </div>
        <div
          style={{ maxWidth: "1152px" }}
          className="bg-white h-1 my-8 w-4/5"
        />
        <div
          style={{ maxWidth: "1152px" }}
          className="w-4/5 mb-16  bg-white h-full"
        >
          <div className=" h-full m-8">
            <p className="">
              write a story about a legendary hero who faught with ancient
              darkness to save a fantasy world with dragons, elfs, dwarfs and
              all sort of mythical beings{" "}
            </p>
            <p className="my-3">...</p>
            <div style={{ background: "#F2F2F2" }}>
              <div className="p-4">
                <p>
                  Once upon a time, in a land far, far away, there was a
                  legendary hero known as Aric. He was a tall, strong and brave
                  warrior who was chosen by the gods to save the fantasy world
                  from ancient darkness that threatened to consume everything in
                  its path.
                </p>
                <div className="mb-2" />
                <p>
                  The world was full of dragons, elves, dwarfs, and all sorts of
                  mythical beings. But the ancient darkness was a force unlike
                  any other. It had been dormant for centuries, but now it had
                  awoken and was spreading rapidly across the land.
                </p>
                <div className="mb-2" />
                <p>
                  Aric knew that he had to act fast. He set out on a journey to
                  find the ancient artifacts that were said to have the power to
                  defeat the darkness. He traveled through treacherous
                  mountains, dark forests, and scorching deserts, facing many
                  dangers along the way.
                </p>
                <div className="mb-2" />
                <p>
                  Finally, after many months of searching, Aric found the
                  artifacts. With them in hand, he set out to confront the
                  ancient darkness.
                </p>
                <div className="mb-2" />
                <p>
                  The battle was fierce and lasted for days. Aric fought
                  bravely, using all of his skill and strength to hold back the
                  darkness. But just when it seemed that all was lost, he used
                  the artifacts to summon a powerful light that banished the
                  darkness forever.
                </p>
                <div className="mb-2" />
                <p>
                  The fantasy world was saved, and the people rejoiced. Aric was
                  hailed as a hero and was showered with gifts and accolades. He
                  returned to his home, but he knew that he would always be
                  remembered as the one who saved the world from ancient
                  darkness.
                </p>
                <div className="mb-2" />
                <p>
                  And so, Aric lived out the rest of his days in peace, knowing
                  that his deeds would be remembered for generations to come. He
                  will always be remembered as a true legendary hero who fought
                  to protect his people and the fantasy world he loved.
                </p>
              </div>
            </div>

            <div className="mb-6" />

            <p>what dangers Aric faced in his journey?</p>
            <p className="my-3">...</p>
            <div style={{ background: "#F2F2F2" }}>
              <div className="p-4">
                During his journey, Aric faced many dangers such as: <br />
                <br /> - ferocious dragons that protected the ancient artifacts
                he was searching for.
                <br />
                - deadly creatures that lurked in the dark forests, such as
                giant spiders and giant snakes.
                <br /> - giant monsters that roamed the scorching deserts.
                <br /> - treacherous mountains, where he had to navigate
                dangerous cliffs and crevices.
                <br /> - hostile tribes that inhabited some of the lands he had
                to cross, who were not friendly to outsiders.
                <br /> - harsh weather conditions, such as sandstorms and
                blizzards, that made his journey even more challenging. <br /> -
                And of course, the ancient darkness itself, which was a
                formidable enemy that he had to face in the final battle. <br />
                <br /> His journey was not an easy one, but Aric's determination
                and bravery helped him overcome these challenges and complete
                his quest to save the fantasy world.
              </div>
            </div>

            <div className="mb-6" />

            <p>describe the ancient artifacts and where each one were found</p>
            <p className="my-3">...</p>
            <div style={{ background: "#F2F2F2" }}>
              <div className="p-4">
                <p>
                  The ancient artifacts that Aric was searching for were three
                  powerful items said to have the power to defeat the ancient
                  darkness. Each artifact had its own unique abilities and were
                  found in different locations:
                </p>
                <div className="mb-2" />
                <p>
                  The Sword of Light: This powerful sword was said to be forged
                  by the gods themselves. It had the ability to emit a brilliant
                  light that could banish the darkness. It was found in a
                  dragon's lair deep in the mountains. Aric had to fight and
                  defeat the dragon to obtain it.
                </p>
                <div className="mb-2" />
                <p>
                  The Shield of Protection: This ancient shield was said to be
                  made of a magical metal that could deflect any attack. It was
                  found in a hidden temple deep in a dense forest. Aric had to
                  solve a series of riddles and puzzles to reach the temple and
                  obtain the shield.
                </p>
                <div className="mb-2" />
                <p>
                  The Staff of Power: This ancient staff was said to have the
                  power to summon a powerful light to banish the darkness. It
                  was found in a desert oasis that was guarded by giant
                  monsters. Aric had to defeat them to reach the oasis and
                  obtain the staff.
                </p>
                <div className="mb-2" />
                <p>
                  With these ancient artifacts in hand, Aric had the power he
                  needed to confront the ancient darkness and save the fantasy
                  world.
                </p>
              </div>
            </div>

            <div className="mb-6" />

            <p>tell more about the world itself</p>
            <p className="my-3">...</p>
            <div style={{ background: "#F2F2F2" }}>
              <div className="p-4">
                <p>
                  The fantasy world in which Aric's story takes place is a vast
                  and varied land, filled with many different races and
                  creatures. Some of the key features of this world include:
                </p>
                <div className="mb-2" />
                <p>
                  Dragons: These powerful creatures are said to be the oldest
                  inhabitants of the world and are known for their intelligence
                  and fierce temper. They are often found guarding treasures and
                  ancient artifacts, such as the Sword of Light.
                </p>
                <div className="mb-2" />
                <p>
                  Elves: These graceful and long-lived beings are known for
                  their skill with magic and their connection to nature. They
                  live in harmony with the forests and are often considered
                  protectors of the natural world.
                </p>
                <div className="mb-2" />
                <p>
                  Dwarfs: These short and sturdy beings are known for their
                  skill in mining and crafting. They live in mountains and
                  underground, and are known for their hardworking and practical
                  nature.
                </p>
                <div className="mb-2" />
                <p>
                  Other mythical beings: The fantasy world is also home to many
                  other mythical creatures such as giants, griffins, unicorns,
                  and centaurs, each with their own unique characteristics and
                  abilities.
                </p>
                <div className="mb-2" />
                <p>
                  Different landscapes: The world has diverse landscapes from
                  snow-capped mountains to scorching deserts, from dark and
                  dense forests to rolling grasslands. Each location has its own
                  unique challenges and dangers.
                </p>
                <div className="mb-2" />
                <p>
                  Different cultures: The fantasy world is also home to many
                  different cultures and civilizations, each with its own unique
                  customs, traditions, and beliefs. Aric's journey takes him
                  through many different lands and he had to adapt to the
                  different cultures and ways of life he encountered.
                </p>
                <div className="mb-2" />
                <p>
                  Overall, the fantasy world is a rich and diverse place, filled
                  with many different races, creatures, and landscapes. It is a
                  place where magic and adventure are commonplace, and where
                  heroes like Aric can make a real difference in the fate of the
                  world.
                </p>
              </div>
            </div>

            <div className="mb-6" />

            <p>
              tell some examples of the cultures present in this fantasy world
            </p>
            <p className="my-3">...</p>
            <div style={{ background: "#F2F2F2" }}>
              <div className="p-4">
                <p>
                  There are many different cultures present in the fantasy
                  world, each with their own unique customs, traditions, and
                  beliefs. Here are a few examples of the cultures that Aric
                  encountered on his journey:
                </p>
                <div className="mb-2" />
                <p>
                  The Dragon Riders: This is a culture of warriors who have
                  tamed dragons and use them as mounts in battle. They are known
                  for their bravery and fierce loyalty to their dragon
                  companions. They live in the mountains and have a strong
                  tradition of dragon riding and training.
                </p>
                <div className="mb-2" />
                <p>
                  The Forest Elves: This culture lives in harmony with nature
                  and is known for their connection to magic and the natural
                  world. They are known for their skill with bow and arrows, and
                  for their knowledge of plants and herbs. They have a strong
                  tradition of storytelling and song.
                </p>
                <div className="mb-2" />
                <p>
                  The Desert Nomads: This culture is adapted to the harsh desert
                  environment, they are known for their survival skills and
                  their ability to find water and food in the desert. They are
                  also known for their horsemanship and their nomadic way of
                  life. They have a strong tradition of storytelling and poetry.
                </p>
                <div className="mb-2" />
                <p>
                  The Dwarfs: This culture lives in the mountains, they are
                  known for their mining and smith skills, their ability to
                  craft weapons and armors. They have a strong tradition of
                  storytelling and singing.
                </p>
                <div className="mb-2" />
                <p>
                  The River People: This culture lives near a big river, they
                  are known for their fishing and boat building skills, they are
                  also known for their traders and merchants. They have a strong
                  tradition of storytelling and music.
                </p>
                <div className="mb-2" />
                <p>
                  These are just a few examples of the many different cultures
                  that exist in the fantasy world. Each culture has its own
                  unique customs, traditions, and beliefs, and Aric had to learn
                  about and adapt to these different cultures during his
                  journey.
                </p>
              </div>
            </div>

            <div className="mb-6" />

            <p>
              can you give more details about the fight between Aric and the
              darkness?
            </p>
            <p className="my-3">...</p>
            <div style={{ background: "#F2F2F2" }}>
              <div className="p-4">
                <p>
                  The final battle between Aric and the ancient darkness was a
                  fierce and epic struggle. The darkness had taken the form of a
                  massive and powerful demon, with eyes that seemed to suck in
                  all light and a voice that shook the very earth.
                </p>
                <div className="mb-2" />
                <p>
                  Aric had the three ancient artifacts he had found during his
                  journey: the Sword of Light, the Shield of Protection, and the
                  Staff of Power. He used the Sword of Light to strike the
                  demon, and the Shield of Protection to deflect its attacks.
                  The Staff of Power, he used it to summon a powerful light that
                  surrounded the demon, weakening it.
                </p>
                <div className="mb-2" />
                <p>
                  The fight was intense and difficult, and Aric was pushed to
                  his limits. He was injured several times, but he kept pushing
                  forward, fueled by his determination to save the fantasy
                  world.
                </p>
                <div className="mb-2" />
                <p>
                  The demon fought back with all its power, unleashing waves of
                  darkness and launching massive fireballs. But Aric's shield
                  protected him, deflecting the darkness and the fireballs. With
                  the sword of light, he was able to strike the demon again and
                  again, weakening it.
                </p>
                <div className="mb-2" />
                <p>
                  Finally, with one last mighty blow, Aric struck the demon with
                  the Sword of Light and the Staff of power. The demon let out a
                  terrible roar and then exploded in a blast of light, banishing
                  the ancient darkness once and for all.
                </p>
                <div className="mb-2" />
                <p>
                  With the darkness defeated, the fantasy world was saved, and
                  Aric was hailed as a hero. He had sacrificed much in his
                  journey, but he had succeeded in his quest to save the world
                  and restore light to the land.
                </p>
                <div className="mb-2" />
                <p>
                  Aric's journey was not only about physical battle but also a
                  mental and emotional one. He had to overcome his doubts, fears
                  and insecurities to become the hero that the world needed. He
                  learned about the different cultures and traditions, and how
                  to work with them, not only for his own advantage but also for
                  the greater good.
                </p>
              </div>
            </div>

            <div className="mb-6" />

            <p>this fantasy world has a name?</p>
            <p className="my-3">...</p>
            <div style={{ background: "#F2F2F2" }}>
              <div className="p-4">
                <p>
                  I apologize, in my previous responses, I did not mention a
                  name for the fantasy world. Let's call this fantasy world
                  "Aeloria". Aeloria is a land of magic and wonder, where
                  dragons soar through the skies, elves live in harmony with
                  nature, and dwarves mine deep in the mountains. It's a place
                  where ancient cultures coexist with one another and where
                  legends and myths are passed down through the generations.
                  It's a world where heroes rise to face the darkness and save
                  their people, like Aric did.
                </p>
              </div>
            </div>

            <div className="mb-6" />

            <p>and what's the name of the ancient darkness? Did it had one?</p>
            <p className="my-3">...</p>
            <div style={{ background: "#F2F2F2" }}>
              <div className="p-4">
                <p>
                  In the legend of Aeloria, the ancient darkness is known as
                  "The Shadow". The Shadow was an ancient and powerful force
                  that threatened to consume the land, extinguishing all light
                  and life. It was said to be a manifestation of pure evil, born
                  from the hatred and despair of the past ages. The Shadow had
                  no physical form, but it could take the shape of whatever it
                  needed to in order to achieve its goals. It was known to be a
                  formidable enemy, and many had tried and failed to defeat it
                  in the past. It was only through Aric's bravery,
                  determination, and the use of the ancient artifacts that The
                  Shadow was finally defeated and peace was restored to Aeloria.
                </p>
              </div>
            </div>

            <div className="mb-6" />

            <p>how can we refer to this story? How is it named?</p>
            <p className="my-3">...</p>
            <div style={{ background: "#F2F2F2" }}>
              <div className="p-4">
                <p>
                  The story of Aric, the legendary hero who fought against The
                  Shadow to save Aeloria, could be referred to as "The Legend of
                  Aric and The Shadow" or simply "Aric and The Shadow". It could
                  also be given a more specific title, such as "The Hero's
                  Journey: Aric and the Ancient Darkness of Aeloria". The name
                  of the story could also be connected to the ancient artifacts,
                  like "The Sword of Light, the Shield of Protection and the
                  Staff of Power: Aeloria's salvation"
                </p>
              </div>
            </div>

            <div className="mb-6" />

            <div className="flex justify-between">
              <div className="w-1/3">
              <Image src={Image1} className="" alt="" height={350} />
              <div className="ml-2 mr-4 mt-2 flex flex-col">
               <small>Prompt</small> 
              <small>a land far away, there was a legendary warrior, he was a tall, strong, brave who was chosen by the gods to save the world from darkness, perfect composition, beautiful detailed intricate insanely detailed octane render trending on artstation, 8 k artistic photography, photorealistic concept art, soft natural volumetric cinematic perfect light, chiaroscuro, award - winning photograph, masterpiece, oil on canvas, raphael, caravaggio, greg rutkowski, beeple, beksinski, giger</small>
              </div>
              
              </div>
              <div className="w-1/3">
              <Image src={Image2} className="" alt="" height={350} />
              <div className="ml-2 mr-4 mt-2 flex flex-col">
               <small>Prompt</small> 
              <small>The Shadow had no physical form building a body shape, in the land, dark, perfect composition, beautiful detailed intricate insanely detailed octane render trending on artstation, 8 k artistic photography, photorealistic concept art, soft natural volumetric cinematic perfect light, chiaroscuro, award - winning photograph, masterpiece, oil on canvas, raphael, caravaggio, greg rutkowski, beeple, beksinski, giger</small>
              </div>
              </div>
              <div className="w-1/3">
              <Image src={Image3} className="" alt="" height={350} />
              <div className="ml-2 mr-4 mt-2 flex flex-col">
               <small>Prompt</small> 
              <small>dwarves in the mountains, magic land, wonder land, mine in the mountains, perfect composition, beautiful detailed intricate insanely detailed octane render trending on artstation, 8 k artistic photography, photorealistic concept art, soft natural volumetric cinematic perfect light, chiaroscuro, award - winning photograph, masterpiece, oil on canvas, raphael, caravaggio, greg rutkowski, beeple, beksinski, giger</small>
              </div>
              </div>
           
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
